import {test} from 'node:test';
import assert from 'node:assert/strict';
import {OilRun,WORLD,oilField} from './game.js';
const blob=(x,y,r=55)=>({x,y,r,vx:0,vy:0,hue:.2,seed:0,cool:0});
test('launch is safe and thrust moves the ship forward',()=>{const g=new OilRun(()=>.5);assert.equal(g.state,'ready');g.start();const y=g.ship.y;for(let i=0;i<60;i++)g.update(1/60,{thrust:true});assert.ok(g.ship.y<y-50);assert.equal(g.state,'playing');});
test('laser splits oil and conserves area',()=>{const g=new OilRun(()=>.5);g.start();g.liquid.drops=[blob(g.ship.x,g.ship.y-150)];const before=g.liquid.drops[0].r**2;for(let i=0;i<20;i++)g.update(1/60,{fire:true});assert.ok(g.cuts>0);assert.equal(g.liquid.drops.length,2);assert.ok(Math.abs(g.liquid.drops.reduce((s,d)=>s+d.r**2,0)-before)<1e-6);});
test('oil contact captures the ship and automatically restarts',()=>{const g=new OilRun(()=>.5);g.start();g.liquid.drops=[blob(g.ship.x,g.ship.y)];g.update(.016,{});assert.equal(g.state,'dying');for(let i=0;i<65;i++)g.update(1/60,{});assert.equal(g.state,'playing');assert.equal(g.attempt,2);assert.equal(g.ship.y,WORLD.startY);});
test('finish requires crossing the striped tape opening',()=>{const g=new OilRun(()=>.5);g.start();g.liquid.drops=[];g.ship.y=WORLD.finishY+1;g.update(0,{});assert.equal(g.state,'playing');g.ship.y=WORLD.finishY-1;g.ship.x=100;g.update(.016,{});assert.equal(g.state,'playing');g.ship.x=550;g.update(.016,{});assert.equal(g.state,'transition');assert.equal(g.transition.kind,'boss');});
test('a blob wake affects the ship and changes direction on schedule',()=>{const g=new OilRun(()=>.75);g.start();const d=blob(g.ship.x+130,g.ship.y,50);g.liquid.drops=[d];g.wakes.set(d,{angle:0,next:1});g.update(.016,{});assert.ok(g.ship.vx<0);for(let i=0;i<70;i++)g.update(1/60,{});assert.notEqual(g.wake(d).angle,0);});
test('collision field follows rendered oil edge',()=>{const d=blob(500,500);assert.ok(oilField([d],500,500,0)>.29);assert.ok(oilField([d],650,500,0)<.29);});
test('long shooting run remains finite and respects the particle budget',()=>{const g=new OilRun(()=>.4);g.start();for(let i=0;i<5000;i++)g.update(1/60,{thrust:true,fire:true,right:i%600<40});assert.ok(g.liquid.drops.length<=48);assert.ok(Number.isFinite(g.ship.x+g.ship.y));});
test('unpiloted oil approaches the player without pointer input',()=>{const g=new OilRun(()=>.5);g.start();const d=blob(200,3000,60);d.vx=0;g.liquid.drops=[d];for(let i=0;i<120;i++)g.update(1/60,{});assert.ok(Math.hypot(d.x-g.ship.x,d.y-g.ship.y)<1500,'oil should gently close the distance without player input');});
test('announced current shift gives a gentle inward surge',()=>{const run=next=>{const g=new OilRun(()=>.5);g.start();const d=blob(550,3000,60);g.liquid.drops=[d];g.wakes.set(d,{angle:0,next,speed:23,surgeUntil:0});for(let i=0;i<60;i++)g.update(1/60,{});return d.vy;};const cruising=run(10),surging=run(.1);assert.ok(surging>cruising);assert.ok(surging<35,'surges should remain gentle');});
test('small fragments explode once for 100 points even with twin hits',()=>{const g=new OilRun(()=>.5);g.start();g.liquid.drops=[blob(500,4000,30)];g.bolts=[0,1].map(()=>({x:500,y:4000,vx:0,vy:-950,life:1}));g.update(0,{});assert.equal(g.liquid.drops.length,0);assert.equal(g.score,100);assert.equal(g.popups.length,1);assert.ok(g.sparks.length>=20);g.reset();assert.equal(g.score,0);assert.equal(g.popups.length,0);});
test('larger blobs still split without scoring',()=>{const g=new OilRun(()=>.5);g.start();g.liquid.drops=[blob(500,4000,55)];g.bolts=[{x:500,y:4000,vx:0,vy:-950,life:1}];g.update(0,{});assert.equal(g.liquid.drops.length,2);assert.equal(g.score,0);});
test('blob speed and eddy strength ramp with course progress',()=>{const run=y=>{const g=new OilRun(()=>.5);g.start();g.ship.y=y;const d=blob(g.ship.x+130,y,50);g.liquid.drops=[d];g.wakes.set(d,{angle:0,next:10,speed:110,surgeUntil:0});g.update(.016,{});return {speed:Math.abs(d.vx),pull:Math.abs(g.current.x),scale:g.intensity};};const start=run(WORLD.startY),end=run(WORLD.finishY+30);assert.equal(start.scale,1);assert.ok(end.scale>1.2&&end.scale<=1.25);assert.ok(end.speed>start.speed*1.15);assert.ok(end.pull>start.pull*1.15);});

test('blobs on every side steer inward even with outward momentum',()=>{for(const [dx,dy] of [[300,0],[-300,0],[0,300],[0,-300]]){const g=new OilRun(()=>.5);g.start();g.ship.y=2500;const d=blob(g.ship.x+dx,g.ship.y+dy,40);d.vx=dx;d.vy=dy;g.liquid.drops=[d];g.update(.016,{});assert.ok(d.vx*(-dx)+d.vy*(-dy)>0);assert.ok(Math.hypot(d.x-g.ship.x,d.y-g.ship.y)<300);}});
test('oil behind the player is retained and keeps pursuing',()=>{const g=new OilRun(()=>.5);g.start();g.ship.y=2000;const d=blob(550,3400,40);g.liquid.drops=[d];g.update(.016,{});assert.equal(g.liquid.drops.length,1);assert.ok(d.vy<0);});

test('normal autonomous drift remains slow',()=>{const g=new OilRun(()=>.5);g.start();const d=blob(550,3000,60);g.liquid.drops=[d];for(let i=0;i<120;i++)g.update(1/60,{});assert.ok(d.y>3015);assert.ok(d.y<3070);assert.ok(Math.hypot(d.vx,d.vy)<35);});
test('releasing thrust retains drift while gradually slowing down',()=>{const g=new OilRun(()=>.5);g.start();g.liquid.drops=[];for(let i=0;i<120;i++)g.update(1/60,{thrust:true});const speed=Math.hypot(g.ship.vx,g.ship.vy),y=g.ship.y;for(let i=0;i<120;i++)g.update(1/60,{});const remaining=Math.hypot(g.ship.vx,g.ship.vy);assert.ok(remaining>speed*.4&&remaining<speed*.55);assert.ok(y-g.ship.y>speed);});
test('turning while coasting keeps momentum, while braking arrests it',()=>{const g=new OilRun(()=>.5);g.start();g.liquid.drops=[];g.ship.vy=-120;for(let i=0;i<30;i++)g.update(1/60,{right:true});assert.ok(Math.abs(g.ship.vx)<1e-8);assert.ok(g.ship.vy<-90);for(let i=0;i<60;i++)g.update(1/60,{brake:true});assert.ok(Math.hypot(g.ship.vx,g.ship.vy)<3);});
test('only small-blob destruction rolls the 5 percent barrel drop',()=>{for(const [roll,expected] of [[0,1],[.049,1],[.05,0],[.099,0],[.9,0]]){const g=new OilRun(()=>roll);g.start();g.liquid.drops=[blob(500,4000,30)];g.bolts=[{x:500,y:4000,vx:0,vy:-950,life:1}];g.update(0,{});assert.equal(g.powerups.length,expected);assert.equal(g.score,100);}const g=new OilRun(()=>0);g.start();g.liquid.drops=[blob(500,4000,55)];g.bolts=[{x:500,y:4000,vx:0,vy:-950,life:1}];g.update(0,{});assert.equal(g.powerups.length,0);});
test('collecting an oil barrel grants one charge and reset clears it',()=>{const g=new OilRun(()=>.5);g.start();g.powerups=[{x:g.ship.x,y:g.ship.y,phase:0}];g.update(0,{});assert.equal(g.nukes,1);assert.equal(g.powerups.length,0);g.update(0,{});assert.equal(g.nukes,1);g.reset();assert.equal(g.nukes,0);});
test('nuke clears only nearby visible oil without points or drops',()=>{const g=new OilRun(()=>0);g.start();g.ship.x=500;g.ship.y=4000;g.nukes=2;g.score=200;g.liquid.drops=[blob(500,4100),blob(695,4000,10),blob(500,4250),blob(900,4000)];const view={x:100,y:3800,w:600,h:600};g.update(0,{nuke:true,view});assert.equal(g.liquid.drops.length,2);assert.ok(g.liquid.drops.every(d=>d.y===4250||d.x===900));assert.equal(g.blast.radius,210);assert.equal(g.nukes,1);assert.equal(g.score,200);assert.equal(g.powerups.length,0);g.update(0,{nuke:true,view});assert.equal(g.nukes,1);});
test('full inventory leaves barrels available until a charge is spent',()=>{const g=new OilRun(()=>.5);g.start();g.nukes=2;g.powerups=[0,1,2].map(()=>({x:g.ship.x,y:g.ship.y,phase:0}));g.update(0,{});assert.equal(g.nukes,3);assert.equal(g.powerups.length,2);g.update(0,{});assert.equal(g.nukes,3);assert.equal(g.powerups.length,2);g.detonate({x:0,y:3800,w:1100,h:1000});assert.equal(g.nukes,2);g.update(0,{});assert.equal(g.nukes,3);assert.equal(g.powerups.length,1);});
test('large viewports cannot increase nuke reach beyond 240',()=>{const g=new OilRun(()=>.5);g.start();g.nukes=1;g.ship.y=2500;g.liquid.drops=[blob(550,2739,10),blob(550,2741,10),blob(550,3500)];g.detonate({x:0,y:0,w:1100,h:4800});assert.equal(g.blast.radius,240);assert.equal(g.liquid.drops.length,2);});
test('nuke requires a charge and a visible playing view',()=>{const g=new OilRun(()=>.5);g.start();const view={x:0,y:0,w:1100,h:4800};assert.equal(g.detonate(view),false);g.nukes=1;assert.equal(g.detonate(null),false);g.state='dying';assert.equal(g.detonate(view),false);assert.equal(g.nukes,1);});
test('nuke can clear danger before oil contact captures the ship',()=>{const g=new OilRun(()=>.5);g.start();g.nukes=1;g.liquid.drops=[blob(g.ship.x,g.ship.y)];g.update(.016,{nuke:true,view:{x:0,y:3800,w:1100,h:1000}});assert.equal(g.state,'playing');assert.equal(g.score,0);assert.equal(g.liquid.drops.length,0);});

test('original finish distance and progress are restored',()=>{const g=new OilRun(()=>.5);g.start();g.liquid.drops=[];assert.equal(WORLD.startY-WORLD.finishY,4250);g.ship.y=3300;g.update(0,{});assert.equal(g.state,'playing');assert.ok(g.progress<.3);g.ship.y=WORLD.finishY-1;g.update(0,{});assert.equal(g.state,'transition');assert.equal(g.transition.kind,'boss');assert.equal(g.progress,1);});
test('course oil roams its home waters, hunts a nearby pilot, and returns when led too far',()=>{const g=new OilRun(()=>.5);g.start();assert.ok(g.liquid.drops.every(d=>d.homeX===d.x&&d.homeY===d.y));for(let i=0;i<3600;i++)g.update(1/60,{});assert.equal(g.state,'playing');assert.ok(g.liquid.drops.every(d=>Math.hypot(d.x-d.homeX,d.y-d.homeY)<360),'idle oil stays dispersed');const d={...blob(550,3000,40),homeX:550,homeY:3000};g.liquid.drops=[d];g.ship.x=550;g.ship.y=3300;g.update(.016,{});assert.ok(d.vy>0,'hunts a pilot within reach');d.y=3360;g.ship.y=3700;g.update(.016,{});assert.ok(d.returning);for(let i=0;i<30;i++)g.update(1/60,{});assert.ok(d.vy<0,'heads home once past its leash');g.liquid.split(d,1,0);assert.equal(g.liquid.drops[1].homeY,3000);});
test('small course oil fires in range every five seconds, never as one volley',()=>{const g=new OilRun(()=>.5);g.start();assert.equal(g.liquid.drops.length,24);g.ship.x=550;g.ship.y=2500;const mk=(x,y,r)=>({...blob(x,y,r),homeX:x,homeY:y,returning:true});const minis=[mk(300,2300,30),mk(800,2300,30)],big=mk(550,2200,60),far=mk(550,1900,30);g.liquid.drops=[...minis,big,far];const shots=[];for(let i=0;i<660;i++){g.enemyBolts=[];g.update(1/60,{});g.ship.x=550;g.ship.y=2500;g.ship.vx=g.ship.vy=0;minis[0].x=300;minis[1].x=800;minis[0].y=minis[1].y=2300;big.x=550;big.y=2200;if(g.enemyBolts.length)shots.push(g.time);assert.ok(g.enemyBolts.length<=1,'one shot at a time');}assert.equal(shots.length,4);assert.ok(shots[1]-shots[0]>=.59&&shots[1]-shots[0]<1);assert.ok(Math.abs(shots[2]-shots[0]-5)<.05);assert.equal(big.nextShot,undefined);assert.equal(far.nextShot,undefined);g.health=25;g.enemyBolts=[{x:550,y:2500,vx:0,vy:0,life:5}];g.update(.016,{});assert.equal(g.state,'dying');assert.ok(g.shot);});
test('each laser hit costs a quarter of the hull; the fourth costs a life and the hull is restored',()=>{const g=new OilRun(()=>.5);g.start();g.liquid.drops=[];const hitShip=()=>{g.enemyBolts=[{x:g.ship.x,y:g.ship.y,vx:0,vy:0,life:5}];g.update(.016,{});};for(const left of [75,50,25]){hitShip();assert.equal(g.health,left);assert.equal(g.state,'playing');assert.equal(g.enemyBolts.length,0);assert.ok(g.events.includes('ship-hit'));assert.equal(g.hullHitAt,g.time);}assert.equal(g.lives,3);g.powerups=[{x:g.ship.x,y:g.ship.y,type:'life',phase:0}];g.update(0,{});assert.equal(g.health,100);assert.equal(g.lives,3);assert.equal(g.powerups.length,0);g.health=25;hitShip();assert.equal(g.state,'dying');assert.equal(g.lives,2);assert.equal(g.health,0);for(let i=0;i<65;i++)g.update(1/60,{});assert.equal(g.state,'playing');assert.equal(g.health,100);g.health=50;g.beginBoss();assert.equal(g.health,100);});
